version: "3"
services:
  db:
    image: postgres:latest
    container_name: meta_db
    ports:
      - "5433:5432"
    volumes:
      - ~/WorkSpace/postgres/metamong/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    privileged: true

  server:
    image: limm0jk/metamong_server:0.1.0
    container_name: metamong_server
    ports:
    - "8080:8080"

